# Generated by Django 5.2.4 on 2025-08-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_rename_chatgroupmessage_groupmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
