# Generated by Django 5.2.4 on 2025-08-30 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='online_user',
            field=models.ManyToManyField(blank=True, related_name='online_users_in_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
