# Generated by Django 5.2.4 on 2025-08-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_chatgroup_online_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='online_user',
            new_name='online_users',
        ),
    ]
